# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'blackbox.gemspec'
    - 'Rakefile'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 17

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 100

Security/Eval:
  Enabled: false
